# Generated by Django 5.2.4 on 2025-07-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_utility_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='card_size',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='layout',
            field=models.CharField(default='grid', max_length=20),
        ),
    ]
