# Generated by Django 5.2.4 on 2025-07-24 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_category_todoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
