# Generated by Django 5.2.4 on 2025-07-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_todoitem_description_todoitem_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='tags',
        ),
    ]
