# Generated by Django 5.2.4 on 2025-07-25 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_todoitem_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
